export const categoryItems = [
    {
      id: 1,
      title: "divine comedy",
      author: "dante alighieri",
      category: "classic",
      price: 20,
      img: "./images/divine comedy.jpg",
      desc: "Belonging in the immortal company of the great works of literature, Dante Alighieri’s poetic masterpiece, The Divine Comedy, is a moving human drama, an unforgettable visionary journey through the infinite torment of Hell, up the arduous slopes of Purgatory, and on to the glorious realm of Paradise—the sphere of universal harmony and eternal salvation.",
    },
    {
      id: 3,
      title: "gargantua and pantagruel",
      author: "francois rabelais",
      category: "classic",
      price: 20,
      img: "./images/gargantua and pantagruel.jpg",
      desc: "Gargantua depicts a young giant, reduced to laughable insanity by an education at the hands of paternal ignorance, old crones and syphilitic professors, who is rescued and turned into a cultured Christian knight. And in Pantagruel and its three sequels, Rabelais parodied tall tales of chivalry and satirized the law, theology and academia to portray the bookish son of Gargantua who becomes a Renaissance Socrates, divinely guided in his wisdom, and his idiotic, self-loving companion Panurge.",
    },
    {
      id: 4,
      title: "the fellowship of the ring",
      author: "j.r.r tolkien",
      category: "fantasy",
      price: 25,
      img: "./images/the fellowship of the ring.jpg",
      desc: "In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, The Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit.",
    },
    {
      id: 5,
      title: "the two towers",
      category: "fantasy",
      author: "j.r.r tolkien",
      price: 25,
      img: "./images/the two towers.jpg",
      desc: "Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.",
    },
    {
      id: 6,
      title: "return of the king",
      author: "j.r.r tolkien",
      category: "fantasy",
      price: 25,
      img: "./images/the return of the king.jpg",
      desc: "To defeat Sauron, the One Ring must be destroyed in the fires of Mount Doom. But the way is impossibly hard, and Frodo is weakening. The Ring corrupts all who bear it and Frodo’s time is running out.",
    },
    {
      id: 7,
      title: "mr mercedes",
      author: "stephen king",
      category: "detective",
      price: 15,
      img: "./images/mr mercedes.jpg",
      desc: "In the predawn hours, in a distressed American city, hundreds of unemployed men and women line up for the opening of a job fair. They are tired and cold and desperate. Emerging from the fog, invisible until it is too late, a lone driver plows through the crowd in a stolen Mercedes, running over the innocent, backing up, and charging again. Eight people are killed; fifteen are wounded. The killer escapes.",
    },
    {
      id: 10,
      title: "northen lights",
      author: "philip pulman",
      category: "fantasy",
      price: 20,
      img: "./images/northen ligths.jpg",
      desc: "Belonging in the immortal company of the great works of literature, Dante Alighieri’s poetic masterpiece, The Divine Comedy, is a moving human drama, an unforgettable visionary journey through the infinite torment of Hell, up the arduous slopes of Purgatory, and on to the glorious realm of Paradise—the sphere of universal harmony and eternal salvation.",
    },
  ];

  